general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = @HOME@/.config/chie-shell/assets/wallpapers/lockscreen.jpg
    blur_passes = 1
    blur_size = 3
    brightness = 0.65
}

label {
    monitor =
    text = $TIME
    color = rgba(eacf52ff)
    font_size = 78
    font_family = @UI_FONT@
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = @HOSTNAME@
    color = rgba(a8d84eff)
    font_size = 19
    font_family = @UI_FONT@
    position = 0, 115
    halign = center
    valign = center
}

label {
    monitor =
    text = @USERNAME@
    color = rgba(dde7c7cc)
    font_size = 13
    font_family = @UI_FONT@
    position = 0, 88
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A  %d %B')"
    color = rgba(899475ff)
    font_size = 14
    font_family = @UI_FONT@
    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 330, 52
    outline_thickness = 2

    dots_size = 0.20
    dots_spacing = 0.28
    dots_center = true

    outer_color = rgba(eacf52cc)
    inner_color = rgba(12160fcc)
    font_color = rgba(dde7c7ff)

    fade_on_empty = false
    placeholder_text = <span foreground="##a8d84e">PASSWORD</span>

    hide_input = false
    rounding = 16

    position = 0, -45
    halign = center
    valign = center
}
