# Chie Shell - Kitty

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.5

background #12160f
foreground #dde7c7

selection_background #a8d84e
selection_foreground #12160f

cursor #eacf52
cursor_text_color #12160f

url_color #a8d84e

color0  #12160f
color1  #d16b5b
color2  #a8d84e
color3  #eacf52
color4  #7fa26d
color5  #b59b6a
color6  #8abf78
color7  #dde7c7

color8  #56604a
color9  #e07b69
color10 #b7e765
color11 #f4dd67
color12 #95b77c
color13 #c6ae7a
color14 #9ed98c
color15 #f0f4e8

background_opacity 0.82
dynamic_background_opacity yes

window_padding_width 10

enable_audio_bell no
confirm_os_window_close 0

tab_bar_style powerline
tab_powerline_style slanted

active_tab_background #a8d84e
active_tab_foreground #12160f
inactive_tab_background #1c2416
inactive_tab_foreground #899475

active_border_color #eacf52
inactive_border_color #465038
